#!/usr/bin/env bash
#
# Run jekyll publish

command="bundle exec jekyll unpublish"
path=$1

if test $# -lt 1; then
  echo "Usage:"
  echo
  echo "   ${0} [post path]"
  echo
  exit
fi

command="$command $path"

echo -e "\n> $command\n"
eval "$command"
